server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/betting
    username: root
    password: MISOwn3r!
    testWhileIdle: true
    validationQuery: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    initialization-mode: never
    platform: mysql
  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

app:
  otp-service:
    expire-time: 3
  otp-provider:
    url: https://2factor.in/API/V1/%s/SMS/91%s/%s
    api-key: 5cac955e-41be-11e9-8806-0200cd936042